accounts/urls.py
from django.urls import path
from .views import SignUpView, edit_custom_user_profile, account_profile_page

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('editprofile/', edit_custom_user_profile, name='editprofile'),
    path('profile/', account_profile_page, name='profile'),
]

events/urls.py
from django.urls import path
from .views import EventListView, EventDetailView, update_event_view, create_event_view

app_name = 'events'
urlpatterns = [
    path('', EventListView.as_view(), name='all_events'),
    path('update/<slug:slug>', update_event_view, name='update_event'),
    path('detail/<slug:slug>', EventDetailView.as_view(), name='event_detail'),
    path('create/', create_event_view, name='create_event'),
]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
'''from django.conf import settings'''
from django.db import models
from django_countries.fields import CountryField

class CustomUser(AbstractUser):
    charity_name = models.CharField(max_length=255)
    charity_address_line_1 = models.CharField(max_length=500)
    charity_address_line_2 = models.CharField(max_length=500)
    charity_postcode = models.CharField(max_length=50)
    charity_website_url = models.URLField(help_text="Please enter a full URL starting with 'http://www...")
    charity_bio = models.TextField(max_length=2000, help_text="Add a short description as to what your charity does and who it benefits.")

    charity_country = CountryField()

    CONTINENT = (
        ('oc', 'We operate mainly in the country the charity is based.'),
        ('af', 'Africa'),
        ('as', 'Asia'),
        ('au', 'Australia/ Oceania'),
        ('eu', 'Europe'),
        ('na', 'North America'),
        ('sa', 'South America'),
    )

    charity_operating_continent = models.CharField(
        max_length=2,
        choices=CONTINENT,
        default='oc',
        help_text='Which continent of the world do you mainly operate in? (Alternatively, select "We operate mainly in the country the charity is based.")'
    )

    charity_image = models.ImageField(upload_to='charities', null=True, help_text='Upload a charity logo.')
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.username

events/models.py
from django.db import models
from django.conf import settings

from django.urls import reverse
from django.utils import timezone

# Create your models here.

class Event(models.Model):
    # This event will be deleted if the user is deleted from the system
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    event_name = models.CharField(max_length=255)
    event_description = models.TextField(max_length=2000)
    event_date = models.DateField()
    event_url = models.URLField(help_text="Enter a url users can visit to learn more.")
    image = models.ImageField(upload_to='events', null=True)
    slug = models.SlugField(null=False, unique=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.event_name

    def get_absolute_url(self):
        return reverse('events:event_detail', kwargs={'slug':self.slug})

    def date_in_future(self):
        return self.event_date >= timezone.now().date()

accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django_countries.fields import CountryField

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 
            'email', 
            'charity_name',
            'charity_address_line_1', 
            'charity_address_line_2',
            'charity_postcode',
            'charity_website_url',
            'charity_bio',
            'charity_country',
            'charity_operating_continent',
            'charity_image',
        )

        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control mb-4 border'}),
            'email':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_name':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_address_line_1':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_address_line_2':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_postcode':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_website_url':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_bio':forms.Textarea(attrs={'class':'form-control  mb-4'}),
            'charity_country':forms.Select(attrs={'class':'form-control form-select mb-4'}),
            'charity_operating_continent':forms.Select(attrs={'class':'form-control form-select mb-4'}),
            'charity_image':forms.FileInput(attrs={'class':'form-control mb-4'}),
            
        }

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 
            'email', 
            'charity_name',
            'charity_address_line_1', 
            'charity_address_line_2',
            'charity_postcode',
            'charity_website_url',
            'charity_bio',
            'charity_country',
            'charity_operating_continent',
            'charity_image',
        )

        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control mb-4 border'}),
            'email':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_name':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_address_line_1':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_address_line_2':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_postcode':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_website_url':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_bio':forms.Textarea(attrs={'class':'form-control  mb-4'}),
            'charity_country':forms.Select(attrs={'class':'form-control form-select mb-4'}),
            'charity_operating_continent':forms.Select(attrs={'class':'form-control form-select mb-4'}),
            'charity_image':forms.FileInput(attrs={'class':'form-control mb-4'}),
            
        }

class EditCustomUserProfileForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            "email",
            "charity_name",
            "charity_address_line_1",
            "charity_address_line_2",
            "charity_postcode",
            "charity_website_url",
            "charity_bio",
            "charity_country",
            "charity_operating_continent",
            "charity_image"
        )

        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control mb-4 border'}),
            'email':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_name':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_address_line_1':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_address_line_2':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_postcode':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_website_url':forms.TextInput(attrs={'class':'form-control mb-4'}),
            'charity_bio':forms.Textarea(attrs={'class':'form-control  mb-4'}),
            'charity_country':forms.Select(attrs={'class':'form-control form-select mb-4'}),
            'charity_operating_continent':forms.Select(attrs={'class':'form-control form-select mb-4'}),
        }

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views import generic

from django.contrib.auth.decorators import login_required
#from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CustomUserCreationForm, CustomUserChangeForm, EditCustomUserProfileForm
from .models import CustomUser
from events.models import Event

from django.http import HttpResponseRedirect
from django.urls import reverse

from django.core.files.uploadedfile import SimpleUploadedFile

# Paginator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

# Custom user can update information about their charity (but not their username and password)
@login_required
def edit_custom_user_profile(request):
    current_user = CustomUser.objects.get(id=request.user.id)

    if current_user.is_staff == True:
        return HttpResponseRedirect('/')

    if request.method == "POST":
        form = EditCustomUserProfileForm(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            current_user.charity_name = form.cleaned_data['charity_name']
            current_user.charity_address_line_1 = form.cleaned_data['charity_address_line_1']
            current_user.charity_address_line_2 = form.cleaned_data['charity_address_line_2']
            current_user.charity_postcode = form.cleaned_data['charity_postcode']
            current_user.charity_website_url = form.cleaned_data['charity_website_url']
            current_user.charity_bio = form.cleaned_data['charity_bio']
            current_user.charity_country = form.cleaned_data['charity_country']
            current_user.charity_operating_continent = form.cleaned_data['charity_operating_continent']
            current_user.charity_image = form.cleaned_data['charity_image']
            current_user.save()
            return HttpResponseRedirect(reverse('accounts:profile'))
        else:
            context = {
                'form':form
            }
    else:
        form = EditCustomUserProfileForm(request.POST or None, request.FILES or None, instance=current_user)
        context = {'form':form}
    
    return render(request, 'accounts/edit_custom_user_profile.html', context=context)

@login_required
def account_profile_page(request):
    current_user = CustomUser.objects.get(id=request.user.id)

    if current_user.is_staff == True:
        return HttpResponseRedirect('/')

    events = Event.objects.all().filter(user=current_user)
    num_events = str(len(events))

    context = {
        'current_user':current_user,
        'events':events,
        'num_events':num_events
    }
    return render(request, 'accounts/profile.html', context=context)

# A charity list view - represented as url - 'all_charities' - see main urls.py
def charity_list_view(request):
    user_list = CustomUser.objects.all().filter(approved=True).filter(is_staff=False).order_by('charity_name')
    
    page = request.GET.get('page',1)
    paginator = Paginator(user_list, 10)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'accounts/charity_list.html', context={'users':users})

accounts/templates/accounts/charity_list.html
{% extends 'base.html' %}

{% block title %}All Charities{% endblock %}

{% block content %}

<div class="container py-5">
	<div class="text-center pb-5">
	    <h2 class="font-weight-bold">All charities</h2>
    </div>
    {% for user in users %}
	<div class="row mb-5">
		<div class="col-md-5 pb-4">
			<h3>{{ user.charity_name }}</h3>
			<img src="{{ user.charity_image.url }}" class="img-fluid" alt="{{ user.charity_name }}">
		</div>
		<div class="col-md-6 pb-4">
			<h5 class="font-weight-bold">CHARITY BIO:</h5>
			<hr>
			<p class="card-text">{{ user.charity_bio|linebreaks }}</p>
		</div>
		<div class="col-md-4 shadow-sm bg-light p-3 mb-4">
			<p class="card-text"><span class="font-weight-bold">COUNTRY: </span>{{ user.charity_country.name }}</p>
		    <p class="card-text"><span class="font-weight-bold">OPERATING IN: </span>{{ user.get_charity_operating_continent_display }}</p>
		    <p class="card-text"><span class="font-weight-bold">WEBSITE URL: </span><a href="{{ user.charity_website_url }}">
		    {{ user.charity_website_url }}</p></a>
		</div>
		<div class="col-md-4 mb-4">
			{% if user.event_set.all %}
			<div class="font-weight-bold card-header">
			    Upcoming Events
			</div>
			<ul class="list-group list-group-flush">
				{% for event in user.event_set.all %}
					{% if event.approved == True and event.date_in_future == True %}
						<li class="list-group-item">
							<a href="{% url 'events:event_detail' event.slug %}">
						    	{{ event.event_name }}
					    	</a>
					    </li>
					{% endif %}
				{% endfor %}
			</ul>
			{% endif %}
		</div>
    </div>
    <hr class="pb-3">
    {% endfor %}
</div>

<div class="container pb-3">
	{% if users.has_other_pages %}
		<ul class="pagination">
			{% if users.has_previous %}
				<li class="page-item">
					<a class="page-link" href="?page={{ users.previous_page_number }}">
						Previous
					</a>
				</li>
			{% endif %}
			{% for i in users.paginator.page_range %}
		        {% if users.number == i %}
		        	<li class="page-item">
		        		<a class="page-link">
		        			<span>{{ i }}<span class="sr-only">(current)</span></span>
		        		</a>
		        	</li>
		        {% else %}
		            <li>
		            	<a class="page-link" href="?page={{ i }}">{{ i }}</a>
		            </li>
		        {% endif %}
		    {% endfor %}
		    {% if users.has_next %}
		    	<li class="page-item">
		    		<a class="page-link" href="?page={{ users.next_page_number }}">Next</a>
		    	</li>
		    {% endif %}
		</ul>
	{% endif %}

</div>

{% endblock %}

accounts/templates/accounts/edit_custom_user_profile.html
{% extends 'base.html' %}

{% block title %}Edit Profile{% endblock %}

{% block content %}

<div class="container py-4">
	<h2 class="font-weight-bold">Update your account settings</h2>

	<p>If you wish to change your password, click <a href="{% url 'password_reset' %}">here</a></p>

	{% if user.is_authenticated %}
	<form method="post" enctype="multipart/form-data">
		{{ form.non_field_errors }}
	  	{% csrf_token %}
	  	{{ form.as_p }}
	  <button class="btn btn-success" type="submit">Update Profile</button>
	</form>
</div>
{% endif %}

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

<!--- django-countries requires calling of template tags ---->
{% load countries %}

{% block title %}Profile{% endblock %}

{% block content %}

<div class="container py-4">
	
	<div class="py-4">
		<a href="{% url 'accounts:editprofile' %}">
	    <button class="btn btn-primary">Edit your Profile</button>
		</a>
		<a href="{% url 'events:create_event' %}">
	    <button class="btn btn-primary">Create an Event</button>
		</a>
	</div>

	<h2 class="font-weight-bold">Your Profile</h2>

	<p><strong>USERNAME: </strong>{{ current_user }}</p>
	<p><strong>EMAIL: {{ current_user.email }}</strong></p>

	<h2>Charity Information</h2>
	<p><strong>CHARITY NAME: </strong>{{ current_user.charity_name }}</p>
	<img src="{{ current_user.charity_image.url }}" class="img-fluid" style="max-width:200px; max-height:150px;" />
	<p><strong>CHARITY ADDRESS:</strong></p>
	<p>{{ current_user.charity_address_line_1 }}</p>
	<p>{{ current_user.charity_address_line_2 }}</p>
	<p>{{ current_user.charity_postcode }}</p>
	<p><strong>COUNTRY: </strong>{{ current_user.charity_country.name }}</p>
	<p><strong>OPERATING IN: </strong>{{ current_user.get_charity_operating_continent_display }}</p>

	<p><strong>WEBSITE URL: </strong>{{ current_user.charity_website_url }}</p>
	<p><strong>BIO (As seen by website visitors): </strong>{{ current_user.charity_bio|linebreaks}}</p>

	<h1>Events:</h1>
	<p>You currently have {{ num_events}} event/s created.</p>

	{% for event in events %}
	<h2>{{ event.event_name }}</h2>
	<p>{{ event.event_description }}</p>
	<p>{{ event.event_date }}</p>
	<a href="{% url 'events:update_event' event.slug %}">Update this event</a>
	<p>----------------</p>

{% endfor %}
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container py-5">
	<div class="text-center pb-4">
		<h2 class="pb-3 font-weight-bold">Sign Up</h2>
	</div>

	<div class="alert-primary p-4 m-3">NOTE: We have to approve all charity signups before they go live on the website. Please allow up to 24 hours. Thank you.</div>
	<form method="post" enctype="multipart/form-data">
	  {% csrf_token %}
	  {{ form.as_p }}
	  <button class="btn btn-success" type="submit">Sign Up</button>
	</form>
</div>
{% endblock %}