accounts/urls.py
from django.urls import path
from .views import SignUpView, edit_custom_user_profile, account_profile_page

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('editprofile/', edit_custom_user_profile, name='editprofile'),
    path('profile/', account_profile_page, name='profile'),
]

charity connect/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from accounts.views import charity_list_view

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('accounts/', include('accounts.urls')),
    path('all_charities/', charity_list_view, name='all_charities'),
    path('events/', include('events.urls')),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

events/urls.py
from django.urls import path
from .views import EventListView, EventDetailView, update_event_view, create_event_view

app_name = 'events'
urlpatterns = [
    path('', EventListView.as_view(), name='all_events'),
    path('update/<slug:slug>', update_event_view, name='update_event'),
    path('detail/<slug:slug>', EventDetailView.as_view(), name='event_detail'),
    path('create/', create_event_view, name='create_event'),
]

charity connect/templates/base.html
{% load static wagtailuserbar %}
{% load wagtailcore_tags %}

<!-- Loads footer template tag from 'templatetags/footer.py' --->
{% load footer %}

<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Bootstrap4 CDN #}
        <!-- CSS only -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

        <!---- Google Fonts ---->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Muli:200,300,400,700)" rel="stylesheet">



        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/charityorganizationsass.css' %}">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}

               <!---Navigation --->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand font-weight-bold" href="{% slugurl 'home' %}">Charity Organization Events</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% slugurl 'home' %}">Home
                            <span class="sr-only"></span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'all_charities' %}">All Charities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'events:all_events' %}">All events</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'search_events' %}">Search Events</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'accounts:profile' %}">
                                    Profile
                                </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'logout' %}">
                                    Log out
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Log In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                            </li>
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}{% endblock %}

        {% get_footer %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/charityorganizationsass.js' %}"></script>

        {# Bootstrap4 JS #}
        <!-- JavaScript Bundle with Popper -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>


        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>